name = "shunt-relay"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "BUNDLES"
id = "073921f695024fdeb844df4770af2946"
preview_id = "8e90f1bd71c34a02bbf5090cf95d178a"

[[routes]]
pattern = "relay.ramcharan.shop"
custom_domain = true

[observability]
enabled = true
